- src/ui/mpv/event.rs
https://mpv.io/manual/stable/#options-input-vo-keyboard
> fix: keyboard input does not work on X11

- libmpv-rs/src/mpv.rs
- libmpv-rs/src/mpv/protocol.rs
- src/config/mod.rs
- src/config/proxy.rs
- src/ui/image.rs
- src/ui/moviedrop.rs
- src/ui/network.rs
- src/ui/new_dropsel.rs
- src/ui/widgets/history.rs
- src/ui/widgets/home.rs
- src/ui/widgets/item.rs
- src/ui/widgets/list.rs
- src/ui/widgets/movie.rs
- src/ui/widgets/settings.rs
- src/ui/widgets/window.rs
+ 给第三方库标记上 allow，省得提示 warning
+ 使用 cargo clippy --fix 自动修改大部分格式
+ 手动调整了两个无法自动修改的问题：
1. ReqClient::new 返回的不是 Self => 更名为 build
2. while let Ok(_) = xxx 推荐改成 while xxx.is_ok() => 照着提示改了
> style: refactor code to pass cargo clippy

- Cargo.lock
- Cargo.toml
- moe.tsuna.tsukimi.gschema.xml
- resources/resources.gresource.xml
- resources/ui/actor.ui
- resources/ui/item.ui
- resources/ui/movie.ui
- resources/ui/settings.ui
- resources/ui/window.ui
- src/config/mod.rs
- src/ui/mod.rs
- src/ui/network.rs
- src/ui/provider/background_paintable.rs
- src/ui/provider/mod.rs
- src/ui/widgets/actor.rs
- src/ui/widgets/history.rs
- src/ui/widgets/home.rs
- src/ui/widgets/item.rs
- src/ui/widgets/list.rs
- src/ui/widgets/mod.rs
- src/ui/widgets/movie.rs
- src/ui/widgets/search.rs
- src/ui/widgets/settings.rs
- src/ui/widgets/window.rs
feat: actor page, recommend list, background, search in current season
chore: refactor series page, movie page
> Update to 0.4.1

- Cargo.lock
- Cargo.toml
- moe.tsuna.tsukimi.gschema.xml
- resources/ui/settings.ui
- resources/ui/window.ui
- src/config/mod.rs
- src/ui/adwaita.css
- src/ui/adwaitadark.css
- src/ui/alpha-dark.css
- src/ui/basic.css
- src/ui/mod.rs
- src/ui/network.rs
- src/ui/provider/background_paintable.rs
- src/ui/provider/mod.rs
- src/ui/solarized.css
- src/ui/style-dark.css
- src/ui/style.css
- src/ui/widgets/actor.rs
- src/ui/widgets/item.rs
- src/ui/widgets/movie.rs
- src/ui/widgets/settings.rs
- src/ui/widgets/window.rs
feat: background blur
chore: organize perferences
> Update to 0.4.2

- Cargo.lock
- Cargo.toml
- resources/ui/item.ui
- resources/ui/movie.ui
- resources/ui/search.ui
- src/config/mod.rs
- src/ui/adwaita.css
- src/ui/adwaitadark.css
- src/ui/alpha-dark.css
- src/ui/basic.css
- src/ui/mod.rs
- src/ui/moviedrop.rs
- src/ui/network.rs
- src/ui/new_dropsel.rs
- src/ui/provider/dropdown_factory.rs
- src/ui/provider/mod.rs
- src/ui/solarized.css
- src/ui/style-dark.css
- src/ui/style.css
- src/ui/widgets/item.rs
- src/ui/widgets/movie.rs
- src/ui/widgets/search.rs
- src/ui/widgets/window.rs
Added:
feat: search recommend
Changed:
chore: refactor search page
chore: refactor play page
fix: improve animation fluency
> Update to 0.4.3

- .github/workflows/build_gnu.yml
- Cargo.lock
- Cargo.toml
- build.rs
- po/zh_CN.po
- src/main.rs
Bring Chinese lang back to Win.
> Fix locale on Windows again

- resources/ui/account_settings.ui
- resources/ui/search.ui
> mpv外部设置翻译补充

- resources/ui/mpv_menu.ui
- src/ui/mpv/page.rs
- src/ui/mpv/tsukimi_mpv.rs
> shutdown when mpv disposed

- installer/tsukimi_installer.nsi
now correctly detecting previous version and correctly display Chinese in prompt.
> fix detecting previous version

- .github/workflows/build_release.yml
`v0.15.2-alpha` makes a pre-release now.
> ci: add pre-release

- src/arg.rs
- src/main.rs
- src/ui/mpv/control_sidebar.rs
- src/ui/mpv/mod.rs
- src/ui/mpv/options_matcher.rs
- src/ui/mpv/tsukimi_mpv.rs
Set adw::ColorScheme after gtk::init, otherwise App will panic.
> set color scheme after gtk init

- build.rs
- src/client/proxy.rs
Fix proxy issue #244 after some code refactoring.
> fix: proxy using AutoConfigUrl

- .github/workflows/build_linux.yml
- .github/workflows/build_release.yml
transfer to arm runner image, make life easier.
> ci: use arm runner image to accelerate arm64 building

- .github/workflows/cargo_clippy_check.yaml
部分feature开了肯定是编译失败的，取消了`--all-features`参数，后续有其他非default feature要开启的时候再手动处理。
> ci: fix clippy check

- resources/ui/mpvpage.ui
- src/client/proxy.rs
- src/lib.rs
- src/main.rs
- src/ui/mpv/mpvglarea.rs
- src/ui/mpv/page.rs
- src/ui/mpv/tsukimi_mpv.rs
unwrapped the Mutex<T> of mpv handle which have marked as `Send` and `Sync`.
> Refactor mpv wrapper

- Cargo.lock
- Cargo.toml
- src/client/emby_client.rs
- src/client/proxy.rs
- src/lib.rs
> Use libproxy on Windows

- .github/workflows/build_release.yml
- README.md
- resources/moe.tsuna.tsukimi.gschema.xml
- resources/ui/account_settings.ui
- src/arg.rs
- src/ui/models/settings.rs
- src/ui/widgets/account_settings.rs
- src/ui/widgets/utils.rs
- src/ui/widgets/window.rs
Due to my incompetence(mainly) and some users extremely harsh criticism, I have decided to drop Windows support.
Closes:
- #250 
Todos:
> Drop Windows support

- .github/workflows/build_windows.yml
revert to default 90 days retention.
> ci: remove retention days

- .github/workflows/build_linux.yml
- .github/workflows/build_release.yml
- .github/workflows/build_windows.yml
> ci: fix secret var name

- src/client/jellyfin_client.rs
> Add server type handling in JellyfinClient authorization
